Repository AY2324S2-CS2103T-W11-1/tp, pull requests merged in 2024-03, with the labels that each got.

#49 Add Hari's information to AboutUs.md page
  docs/AboutUs.md
  docs/images/hm33-stu.png
  docs/team/hm33-stu.md
Labels: type.Task

#51 Add Use Cases (and Stories) To DG
  docs/DeveloperGuide.md
Labels: type.Task

#50 Amend Add and Delete details in the User Guide
  docs/UserGuide.md
Labels: type.Task

#109 Add simple find commands
  src/main/java/seedu/address/logic/commands/InternshipFindCommand.java
  src/main/java/seedu/address/logic/parser/InternshipFindCommandParser.java
  src/test/java/seedu/address/logic/commands/InternshipFindCommandTest.java
  src/test/java/seedu/address/logic/parser/InternshipFindCommandParserTest.java
Labels: priority.High

#111 Logic manager and internship data parser
  src/main/java/seedu/address/logic/InternshipLogic.java
  src/main/java/seedu/address/logic/InternshipLogicManager.java
  src/main/java/seedu/address/logic/parser/InternshipDataParser.java
  src/test/java/seedu/address/logic/InternshipLogicManagerTest.java
  src/test/java/seedu/address/logic/parser/InternshipDataParserTest.java
  src/test/java/seedu/address/testutil/InternshipUtil.java
Labels: priority.High

#119 Set result display to wrap text, make colour styling functional for different statuses
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/InternshipCard.fxml
Labels: priority.Medium
