Repository AY2324S2-CS2103T-W11-1/tp, pull requests merged in 2024-04, with the labels that each got.

#126 Add clickable internship, Tests for UI
  build.gradle
  src/main/java/seedu/address/logic/InternshipLogic.java
  src/main/java/seedu/address/logic/InternshipLogicManager.java
  src/main/java/seedu/address/logic/commands/InternshipAddDeadlineCommand.java
  src/main/java/seedu/address/model/InternshipModel.java
  src/main/java/seedu/address/model/InternshipModelManager.java
  src/main/java/seedu/address/ui/DetailedInternshipCard.java
  src/main/java/seedu/address/ui/DetailedInternshipListPanel.java
  src/main/java/seedu/address/ui/DetailedInternshipWindow.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/InternshipListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DetailedInternshipCard.fxml
  src/main/resources/view/DetailedInternshipWindow.fxml
  src/test/java/seedu/address/logic/commands/InternshipAddCommandTest.java
  src/test/java/seedu/address/ui/DetailedInternshipCardTest.java
  src/test/java/seedu/address/ui/DetailedInternshipListPanelTest.java
  src/test/java/seedu/address/ui/InternshipCardTest.java
  src/test/java/seedu/address/ui/UiTestBase.java
Labels: priority.High

#177 Improve Find error messages, add support for remark, add tests for InternshipParserUtil
  .gitignore
  src/main/java/seedu/address/logic/commands/InternshipFindCommand.java
  src/main/java/seedu/address/logic/parser/InternshipAddCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipFindCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipParserUtil.java
  src/main/java/seedu/address/model/internship/InternshipContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/InternshipFindCommandTest.java
  src/test/java/seedu/address/logic/parser/InternshipFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternshipParserUtilTest.java
  src/test/java/seedu/address/model/internship/InternshipContainsKeywordsPredicateTest.java
Labels: priority.High

#185 Updated Optional Feature
  src/main/java/seedu/address/logic/commands/InternshipAddCommand.java
  src/main/java/seedu/address/logic/parser/InternshipAddCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipEditCommandParser.java
  src/main/java/seedu/address/logic/parser/InternshipParserUtil.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/Location.java
  src/main/java/seedu/address/model/internship/Role.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/test/java/seedu/address/logic/InternshipLogicManagerTest.java
  src/test/java/seedu/address/logic/parser/InternshipAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternshipDataParserTest.java
  src/test/java/seedu/address/logic/parser/InternshipEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternshipParserUtilTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/LocationTest.java
  src/test/java/seedu/address/model/internship/RoleTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/InternshipUtil.java
Labels: type.Task, priority.High

#310 Fix null invocation bug
  src/main/java/seedu/address/logic/commands/InternshipEditCommand.java
  src/main/java/seedu/address/model/InternshipModelManager.java
Labels: priority.High, type.Bug
